Dish_Discoveries/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from django.contrib.auth import views as auth_views
#
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', users_views.profilepage, name='profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views


app_name = 'food'
urlpatterns = [
    path('', views.IndexItem.as_view(), name='index'), 
    path('<int:pk>/', views.DetailItem.as_view(), name='detail'),  #detail view 
    path('add/', views.CreateItem.as_view(), name='create'),  # add items
    path('update/<int:id>/', views.update, name='update'),  # update items
    path('delete/<int:id>/', views.delete, name='delete'),  # delete items
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):
    
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=500)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=700, default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8GV0f6prb-DPesR3lFwG2UsJh94yNz7ijRQ&usqp=CAU")
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self) -> str:
        return self.item_name
    
    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta():
        model = User
        fields = ['username', 'email', 'password1', 'password2',]

food/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.views.generic import ListView, DetailView, CreateView


class IndexItem(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def item(request):
    return HttpResponse("Hello world")


class DetailItem(DetailView):
    model = Item
    template_name = 'food/detail.html'

# def create(request):
#     form = ItemForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
    
#     return render(request, 'food/item-form.html', {'form': form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form': form, 'item':item})


def delete(request, id):
    item = Item.objects.get(id=id)

    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item':item})

users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome to Dish Discoveries {username}')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})


@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-sm  bg-dark border-bottom " data-bs-theme="dark">
        <a href="{% url 'food:index' %}" class="navbar-brand mb-lg-1 h1">Dish Discoveries</a>
        <div class="container-fluid">
            <ul class='nav navbar ms-auto'>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'food:create' %}">Add Item</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'profile' %}" class="nav-link">Profile</a>
                    </li>
                        <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="nav-link">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="card" height="300" width="450" src="{{ item.item_image }}">
            </div>
            <div class="col-md-6">
                <h3>{{ object.item_name }}</h3>
                <h4>{{ object.item_desc }}</h4>
                <h5>₹{{ object.item_price }}</h5><br>
                <a class="btn btn-secondary" href="{% url 'food:update' item.id %}">Update</a></b>
                <a class="btn btn-primary" href="{% url 'food:delete' item.id %}">Delete</a>
            </div>
        </div>
    </div>
    
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}
    {% for item in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="150" width="250" src="{{ item.item_image }}">
        </div>
        <div class="col-md-3">
            <h3>{{ item.item_name }}</h3>
            <h4>{{ item.item_desc }}</h4>
            <h5>₹{{ item.item_price }}</h5>
            <h6>{{ item.user_name }}</h6><br>
        </div>
        <div class="col-md-3">
            <br><a class="btn btn-secondary" href="{% url 'food:detail' item.id %}">Details</a>
        </div>
    </div>
    {% endfor %}

{% endblock %}

food/templates/food/item-delete.html
{% extends 'food/base.html'%}

{% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h3>Do you really want to delete {{ item.item_name }}</h3>
        <a type="submit" class="btn btn-secondary" href="{% url 'food:index' %}">Cancel</a></b>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </form>
</div>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title">Add Item</div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <br><button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!-- <div class="container">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
</div> -->

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info">
                        <div class="card-title">Login</div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-info" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/logout.html
<div class="container">
    <h1>Thanks for visting our website.</h1>
</div>

users/templates/users/profile.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <h1>{{ user.username }}</h1>
    <img src="{{ user.profile.image.url }}" height="120">
</div>
{% endblock %}    

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title">Register</div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <br><button type="submit" class="btn btn-primary">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}